---
- name: Get users home
  become: true
  command: echo ~{{ item }}
  register: user_home_result
  check_mode: false
  changed_when: false

- name: Set users home
  set_fact:
    user_home: "{{ user_home_result.stdout }}"

- name: Check if users home exists
  become: true
  stat:
    path: "{{ user_home }}"
  register: file_details

- name: Write inputrc for user {{ item }}
  become: true
  template:
    src: inputrc.j2
    dest: "{{ user_home }}/{{ inputrc_file }}"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
    backup: true
  when: file_details.stat.exists
  vars:
    options: "{{ inputrc_options }}"
    bindings: "{{ inputrc_bindings }}"
    include: "{{ inputrc_include }}"
